server:
  port: 5002

spring:
  application:
    name: ms-dashboard

eureka:
  instance:
    preferIpAddress: false
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
